### ISSUE TITLE
runtime error running example

### ISSUE THREAD

**Issue by haishao** [ua-parser/uap-scala#10]
Followed the README to build the package and tried running the example in README in sbt and got following error:

scala> import org.uaparser.scala.Parser
import org.uaparser.scala.Parser

scala> val ua = "Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B206 Safari/7534.48.3"
ua: String = Mozilla/5.0 (iPhone; CPU iPhone OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B206 Safari/7534.48.3

scala> val client = Parser.get.parse(ua)
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
  at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
  at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
  at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
  at org.uaparser.scala.Parser$.create(Parser.scala:22)
  at org.uaparser.scala.Parser$.get(Parser.scala:31)
  ... 43 elided
Caused by: java.io.IOException: Stream closed
  at java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
  at java.io.PushbackInputStream.read(PushbackInputStream.java:166)
  at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
  at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
  at java.io.Reader.read(Reader.java:140)
  at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
  ... 47 more

Btw, it looks like no yaml files exist in the code base.

**Comment by haishao** [comment]
user error.  missed step

cd core
git submodule update --init --recursive

**Comment by humanzz** [comment]
I take it that your problem was solved with this last step?

Let me know if you are still having any problems.
