### ISSUE TITLE
frequently getting  NoClassDefFoundError  : scala/Product$class

### ISSUE THREAD

**Issue by abhisheksahani** [ua-parser/uap-scala#32]
hi i am using uap-scala_2.10-0.1.0.jar 
we are frequently getting following error

java.lang.NoClassDefFoundError: scala/Product$class
        at org.uaparser.scala.UserAgent$UserAgentPattern.<init>(UserAgent.scala:14)
        at org.uaparser.scala.UserAgent$UserAgentPattern$$anonfun$fromMap$2.apply(UserAgent.scala:35)
        at org.uaparser.scala.UserAgent$UserAgentPattern$$anonfun$fromMap$2.apply(UserAgent.scala:34)
        at scala.Option.map(Option.scala:146)
        at org.uaparser.scala.UserAgent$UserAgentPattern$.fromMap(UserAgent.scala:34)
        at org.uaparser.scala.UserAgent$UserAgentParser$$anonfun$fromList$1.apply(UserAgent.scala:48)
        at org.uaparser.scala.UserAgent$UserAgentParser$$anonfun$fromList$1.apply(UserAgent.scala:48)
        at scala.collection.immutable.List.map(List.scala:283)
        at org.uaparser.scala.UserAgent$UserAgentParser$.fromList(UserAgent.scala:48)
        at org.uaparser.scala.Parser$.create(Parser.scala:26)
        at org.uaparser.scala.Parser$.get(Parser.scala:31)
        at org.uaparser.scala.Parser.get(Parser.scala)
        at com.games24x7.ups.rc.utils.CollectionsUtil.getParsedUserAgent(CollectionsUtil.java:112)
        at com.games24x7.ups.rc.eventhandlers.LoginEventHandler.handleEvent(LoginEventHandler.java:101)
        at com.games24x7.ups.core.ProcessEvent.lambda$manageEvent$1(ProcessEvent.java:101)
        at java.util.ArrayList.forEach(ArrayList.java:1249)

**Comment by travisbrown** [comment]
That looks like you've somehow got either multiple scala-library jars or the wrong one for your uap-scala version.

**Comment by abhisheksahani** [comment]
got it thanks for quick reply
